Name:           ros-lunar-test-osm
Version:        0.2.4
Release:        0%{?dist}
Summary:        ROS test_osm package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/test_osm
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-geodesy
Requires:       ros-lunar-geographic-msgs
Requires:       ros-lunar-osm-cartography
Requires:       ros-lunar-route-network
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-geodesy
BuildRequires:  ros-lunar-geographic-msgs
BuildRequires:  ros-lunar-osm-cartography
BuildRequires:  ros-lunar-route-network

%description
These are regression tests for the osm_cartography and route_network packages.
They are packaged separately to avoid unnecessary implementation dependencies.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Wed Dec 06 2017 Jack O'Quin <jack.oquin@gmail.com> - 0.2.4-0
- Autogenerated by Bloom

